title: Marcello Nesca's Data Science Enthusiast Portfolio
author: Marcello Nesca
email: umnescam@myumanitoba.ca
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  This personal website will be my personal portfolio along with CV and contact information. 
  My goal is to try to make data science/analytics fun and accessible to everyone who is interested in learning.
  I enjoy giving public lectures and showing how cool and fun coding and analytics can be!
  I hope you enjoy my site!
# social links
twitter_username: marcellonescafe # DO NOT include the @ character, or else the build will fail!
github_username:  mnesca # DO NOT include the @ character, or else the build will fail!
linkedin_username: marcellonesca
show_excerpts: true # set to false to remove excerpts on the homepage
